### ISSUE TITLE
Filament sensor on mk3s firmware does not work

### ISSUE THREAD

**Issue by Truetech000** [bgiot/Prusa-Firmware-BMG#6]
As stated, the sensor is not working on the custom firmware for mk3s 1.8

**Comment by bgiot** [comment]
Which release did you try ?

**Comment by Truetech000** [comment]
Mk3s 1.8 degree step

**Comment by Truetech000** [comment]
Latest

**Comment by bgiot** [comment]
Did you try the stock firmware for MK3S (make sure to set e-steps to 830) ? is IR sensor working?
Because I checked again the different configs for each firmware version build and all seem ok... maybe you have a hardware issue ?  As I don't have the S upgrade on my MK3, I cannot do any testing... sorry, I'll need your help to figure-out what's going on...

**Comment by Truetech000** [comment]
It does work with stock, I am curious what all is changed with your fw
other than e steps and z distance?

**Comment by bgiot** [comment]
I checked and only e-steps, z distance, and speeds for load/unload are changed....
When my firmware installed, does the screen displays 'Prusa BMG MK3S' ?

**Comment by Truetech000** [comment]
I'm sorry, I found the issue. It was that the magnets in the add-on from
bondtech are too far apart in their design, I will be modifying it to make
them engage.

**Comment by bgiot** [comment]
So, wait your confirmation that my custom firmware works fine to close the issue

**Comment by Truetech000** [comment]
Yes, thanks again and sorry for the inconvenience

**Comment by bgiot** [comment]
Issue closed because not an issue
